# Maintenance:
#   - Keep `DOTNET_VERSION` updated to the latest stable dotnet version
#   - Synchronize the `configuration` matrix with the list of
#     configurations defined in the project solution
#   - Adjust `retention-days` to the preference of the repository owner

name: Validate

env:
  DOTNET_VERSION: 8.x
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

on:
  push:
    branches:
      - main
  pull_request:
    # All types excluding draft
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Debug Tiles
          - Debug Tilesanity
          - Release
          - Release Tilesanity

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: |
            StardewArchipelago/packages.lock.json
            StardewArchipelagoTests/packages.lock.json
      - run: dotnet restore --locked-mode

      - uses: actions/cache@v4
        with:
          path: '**/obj'
          key: ${{ runner.os }}-${{ matrix.configuration }}-obj-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.configuration }}-obj-

      - name: build (${{ matrix.configuration }})
        run: dotnet build --no-restore -p:ContinuousIntegrationBuild=true -p:EnableModDeploy=false -p:EnableModZip=false -p:EnableGameDebugging=false -p:BundleExtraAssemblies=false -c "${{ matrix.configuration }}"

      - id: test
        if: startsWith(matrix.configuration, 'Release')
        run: dotnet test --no-build -c "${{ matrix.configuration }}" --logger "junit;LogFileName=test-results.xml" --results-directory test_results/"${{ matrix.configuration }}"

      - name: upload_test_results
        if: startsWith(matrix.configuration, 'Release')
        uses: actions/upload-artifact@v4
        with:
          name: test_results_${{ matrix.configuration }}
          path: test_results/"${{ matrix.configuration }}"
          retention-days: 30
