# Maintenance:
#   - Keep `DOTNET_VERSION` updated to the current LTS version: https://dotnet.microsoft.com/en-us/platform/support/policy
#   - Whenever SDV and/or SMAPI is updated, update `SDV_VER` and `SMAPI_VER` to match the tag from https://github.com/StardewModders/mod-reference-assemblies/tags
#   - Keep the `configuration` matrix list synchronized with the build configurations defined in `StardewArchipelago.csproj`

name: Validate

env:
  DOTNET_VERSION: 8.x
  REF_DLLS_REPO: StardewModders/mod-reference-assemblies
  SDV_VER: 1.6.15
  SMAPI_VER: 4.2.1

  REF_DLLS_PATH: ${{ github.workspace }}/reference-assemblies
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

on:
  push:
    branches:
      - main
  pull_request:
    # All types excluding draft
    types: [opened, synchronize, reopened, ready_for_review]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write

    strategy:
      fail-fast: false
      matrix:
        configuration:
          - Debug
          - Debug Tiles
          - Debug Tilesanity
          - Release
          - Release Tilesanity

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: checkout_ref_assemblies
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REF_DLLS_REPO }}
          path: '${{ env.REF_DLLS_PATH }}'
          ref: 'SDV${{ env.SDV_VER }}-SMAPI${{ env.SMAPI_VER }}'
          fetch-depth: 0

      - name: setup_dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          cache: true
          cache-dependency-path: |
            StardewArchipelago/packages.lock.json
            StardewArchipelagoTests/packages.lock.json

      - name: dotnet restore
        run: dotnet restore --locked-mode

    #   - uses: actions/cache@v4
    #     with:
    #       path: '**/obj'
    #       key: ${{ runner.os }}-${{ matrix.configuration }}-obj-${{ github.sha }}
    #       restore-keys: |
    #         ${{ runner.os }}-${{ matrix.configuration }}-obj-

      - name: dotnet_build (${{ matrix.configuration }})
        run: dotnet build --no-restore -p:ContinuousIntegrationBuild=true -p:EnableModDeploy=false -p:EnableModZip=false -p:EnableGameDebugging=false -p:BundleExtraAssemblies=false -p:GamePath="${{ env.REF_DLLS_PATH }}" -c "${{ matrix.configuration }}"

      - name: dotnet_test (${{ matrix.configuration }})
        if: ${{ matrix.configuration == 'Release' }}
        run: dotnet test --no-build --no-restore -c Release
